name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: ldid install
      run: brew install ldid
    - name: make
      run: make TARGET=ios
    - name: ls
      run: ls
    - name: zip file
      run: cd ./ChOma/output/ && zip -r xxx.zip ./
      
